### ISSUE TITLE
Inconsistency.

### ISSUE THREAD

**Issue by K0-RR** [ndrp/faster-minecarts#6]
From mod's curseforge description:
> This mod adds the option to increase the speed of **vanilla minecarts** from **8** m/s up to 30m/s.

In the ModMenu it's stated that the vanilla value is 0 and it can't be set more than 12.

**Comment by Falconjh** [comment]
This is because this line:

`cir.setReturnValue(0.4 + config.maxSpeed / 10D);`

is incorrect. If it were 

`cir.setReturnValue(config.maxSpeed/20D);`

then the config max speed would be the max speed that the minecart can travel at (which technically doesn't need to be capped at 30 b/s, that's a minecraft MoveOnRail limit because it is checking for the next rail block and running each tick, so that the max movement is 1.5 blocks per tick (so that it never moves 2 blocks per tick)).

In fact, setting the value to the max of 12 gives 32 b/s if it weren't for what moveOnRail is doing.

**Comment by faultycore** [comment]
>This is because this line:
cir.setReturnValue(0.4 + config.maxSpeed / 10D);
is incorrect

I wouldn't call it 'incorrect' exactly, it's just that I apparently forgot to update the description of the mod to 32 m/s. Btw, I did it this way and not the way you suggest because I wanted the options to go from base speed to max modded speed - which is where the constant term comes from. For some reason I didn't want the user to be able to set the speed _below_ vanilla speed.

So I will close this issue, since the mod does actually increase the speed to (roughly) 30 m/s, the options slider is simply an (admittedly confusing) value that doesn't represent the actual speed in m/s, but is simply a scaling factor.

**Comment by parthier** [comment]
Intended
